### ISSUE TITLE
SQL type BIT is treated as SHORT_INT, not BOOLEAN?

### ISSUE THREAD

**Issue by yuj** [lwhite1/tablesaw#100]
In SqlResultSetReader, it maps the SQL BIT type (for boolean purpose) to Tablesaw's ColumnType.SHORT_INT.  This mapping causes exception when reading a ResultSet containing a BIT (boolean) column.

A workaround I put locally is to implement the SqlResultSetReader.read() method myself by providing a modified version of SQL_TYPE_TO_TABLESAW_TYPE that maps Types.BIT to ColumnType.BOOLEAN, instead of ColumnType.SHORT_INT.

I am wondering if this is also an issue for others and if my workaround solution deserves a pull request.

**Comment by lwhite1** [comment]
I think that you're correct that bit will in most cases be used for boolean values,  so I made the mapping change in the original SQL_TYPE_TO_TABLESAW_TYPE.  The fix is in v. 0.7.6.7.

**Comment by yuj** [comment]
:+1:
