### ISSUE TITLE
Intro documentaton: show required imports

### ISSUE THREAD

**Issue by hmf** [lwhite1/tablesaw#101]
Hello,

Just started using the library. So far so good. However when I picked up the introductory documentation [here](https://jtablesaw.wordpress.com/) I could not immediately use the examples in a Scala REPL because of missing imports such as:

    import com.github.lwhite1.tablesaw.api.Table
    import com.github.lwhite1.tablesaw.api.QueryHelper.column
    import com.github.lwhite1.tablesaw.api.QueryHelper.anyOf
    import com.github.lwhite1.tablesaw.reducing.CrossTab

It would be nice if these could be added to the examples. 

Regards

**Comment by lwhite1** [comment]
Sorry for the difficulty. I will put this on my todo list.
