### ISSUE TITLE
Question: counting relative frequency

### ISSUE THREAD

**Issue by hmf** [lwhite1/tablesaw#102]
Hello,

I would like to know if their is any call that can calculate the relative frequency of the items in a column.

I see that many of the column objects provide a asSet method, which easily allows one to calculate the frequencies. However when we use a table we generally access the column as a generic Column. How should one access the asSet method without encoding the column type?

Additionally for the real numbers, the asSet understandably does not exist. Any suggestions how I could do this?

TIA

**Comment by lwhite1** [comment]
For columns that are not floats, you can use the (admittedly hacky) approach of using "cross tabs" on the column of interest (passing it into the method twice), and calculating the column percents. This will give you a column at the end of the table ("total") that has the value you're looking for

```
 Table xtab = CrossTab.xCount(t, t.column("Scale"), t.column("Scale"));
 Table cPct = CrossTab.columnPercents(xtab);
 System.out.println(cPct.print());

```
```
    Crosstab Column Proportions:
           -9  0   1   2   3   4   5   total
    -9    1.0 0.0 0.0 0.0 0.0 0.0 0.0 9.508716E-4
    0     0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.45545083
    1     0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.33459005
    2     0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.15203936
    3     0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.043773457
    4     0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.011727417
    5     0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0014680123
    Total 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0

```

This doesn't work on floats. For floats I think you would have to implement yourself using either rounding or an equality test that allows for imperfect matching

**Comment by hmf** [comment]
Thank you. In regards to the floats I am only attempting to check for existence of possibly nominal features so my code simply uses exact matching.
