### ISSUE TITLE
Auto-detecting Column Type: prevent failure by reporting unknown type

### ISSUE THREAD

**Issue by hmf** [lwhite1/tablesaw#103]
Hello,

I am reading a wide CSV file (342 columns) and it fails because the sampling does not work. This causes several issues: identifying the types/incorrect column and correcting the problem.  I have seen #8, which mentions  `CsvReader.detectedColumnTypes`. However this function keeps on failing so even though we see the error it is not easy to construct the array of ColumnType and use that to keep loading and correcting any other problems.

I would suggest the following changes:

1. Place a flag so that all of the file is read for column type inference (not just a sample). 
2. Let `CsvReader.detectedColumnTypes` complete all columns and return a SKIP on an unknown type
3. Let `CsvReader.detectedColumnTypes` accept an array of ColumnType  

This way we can use (1) and (2) to get the correct types so that we can load the file using that as a parameter. Alternatively we can use (2) and (3) and manually keep correcting the ColumnType until all parsing is correct.

At this point in time all I could do was add a value in the first line (seems to always sample the firs line) to correct the parse, get the types and then use that on the original file.  Maybe there is another more effective and efficient way to solve this?

TIA

**Comment by hmf** [comment]
I have just realised that their is a version of `CsvReader.detectedColumnTypes` that already returns the types. Can we make it public?

**Comment by lwhite1** [comment]
I made  CsvReader.detectedColumnTypes public (on master). Does that resolve the issue for you?

**Comment by lwhite1** [comment]
This change is now in v. 0.7.6.7 which should be available on maven central "soon". (It seems to take hours to get there.)

**Comment by hmf** [comment]
Doesn't quite solve the issue but make it easier on my side. Any way we can call this function without  using sampling (using the full dataset)? My problem is that I have a large file and sampling does not seem to infer the correct type. Once again, thanks.

**Comment by lwhite1** [comment]
I should have mentioned that there is a public method in CsvReader, called printColumnTypes() that produces a string that can be cut and pasted into code as an array literal. You can fix errant column types in that string and then pass it into a Table constructor that will then do no (additional) column type 
detection. 

 
```
  /**
   * Returns a string representation of the file types in file {@code csvFilename},
   * as determined by the type-detection algorithm
   * <p>
   * This method is intended to help analysts quickly fix any erroneous types, by printing out the types in a format
   * such that they can be edited to correct any mistakes, and used in an array literal
   * <p>
   * For example:
   * <p>
   * LOCAL_DATE, // 0     date
   * SHORT_INT,  // 1     approval
   * CATEGORY,   // 2     who
   * <p>
   * Note that the types are array separated, and that the index position and the column name are printed such that
   * they would be interpreted as comments if you paste the output into an array:
   * <p>
   * ColumnType[] types = {
   * LOCAL_DATE, // 0     date
   * SHORT_INT,  // 1     approval
   * CATEGORY,   // 2     who
   * }
   */
   public static String printColumnTypes(String csvFileName, boolean header, char delimiter)
```

**Comment by lwhite1** [comment]
and to add to the above, i implemented your suggested enhancement of including full dataset in the detection process. 

```
/**
   * Returns a new table constructed from a character delimited (aka CSV) text file
   * <p>
   * It is assumed that the file is truly comma-separated, and that the file has a one-line header,
   * which is used to populate the column names
   *
   * @param csvFileName The name of the file to import
   * @param header      True if the file has a single header row. False if it has no header row.
   *                    Multi-line headers are not supported
   * @param delimiter   a char that divides the columns in the source file, often a comma or tab
   * @param skipSampling  This applies only to column type detection. Column type detection uses sampling to pick a
   *                      column type. This may cause the algorithm to skip a row that has information the algorithm
   *                      needs. Setting this to true will cause the algorithm to check jjjjbhball the data in the table,
   *                      which may take a long time (a couple minutes?) on large tables (over 100,000,000 rows).
   * @throws IOException
   */
  public static Table createFromCsv(String csvFileName, boolean header, char delimiter, boolean skipSampling)
      throws IOException {
    return CsvReader.read(csvFileName, header, delimiter, skipSampling);
  }

```

**Comment by hmf** [comment]
@lwhite1 In regards to `printColumnTypes()` I was using something similar but more convoluted:  I would call `CsvReader.detectedColumnTypes`, look at the values in the "Column Type" column and convert those to `ColumnType`. I would then use ` Table.createFromCsv` and pass it those column types. This would be done iteratively until I the types seemed to be ok.  

In regards to  `createFromCsv` I already have version "0.7.6.9" so I am going to use this solution. Hopefully I will not have "force" any column type. 

I have a question regarding the latest changes,  hope it is ok to ask them, here:

When recompiling my stuff I see that a `ColumnType.DOUBLE`was introduced. However I do not see any `Table.doubleColumn`, do we still use `Table.floatColumn` here?

Thank you very much for the changes.

**Comment by hmf** [comment]
@lwhite1 Tried "0.7.6.9" but did not find the `skipSampling` version of the `Table.createFromCsv`. Can you confirm that it is was included in this release. TIA.

**Comment by lwhite1** [comment]
Good chance it is still on master and not deployed

Will try to check it tonight

**Comment by lwhite1** [comment]
I need to add that and probably do some more work to get it fully
integrated.   Dealing with primitves is a lot of work

doubleColumn is just syntactic sugar on

(DoubleColumn) table.column(1);

to do the cast.

Ill add the method soon.

**Comment by hmf** [comment]
@lwhite1 Ok then I will wait for the release, change my code and tests and give you feedback. If all is ok I will close this issue.

**Comment by lwhite1** [comment]
Sounds good. Thanks.

**Comment by hmf** [comment]
@lwhite1 I have attempted to use the newest version and have the following exception:

```
com.github.lwhite1.tablesaw.io.csv.AddCellToColumnException: Error while addding cell from row 26 and column D.Dr03(position:258): D.Dr03: For input string: "53.563"
[info]   at com.github.lwhite1.tablesaw.io.csv.CsvReader.read(CsvReader.java:149)
[info]   at com.github.lwhite1.tablesaw.io.csv.CsvReader.read(CsvReader.java:76)
[info]   at com.github.lwhite1.tablesaw.io.csv.CsvReader.read(CsvReader.java:96)
[info]   at com.github.lwhite1.tablesaw.api.Table.createFromCsv(Table.java:846)
[info]   at pt.inescn.utils.TableSawUtilsSpec.$anonfun$new$6(TableSawUtilsSpec.scala:107)
[info]   at pt.inescn.utils.Utils$.time(Utils.scala:10)
[info]   at pt.inescn.utils.TableSawUtilsSpec.$anonfun$new$5(TableSawUtilsSpec.scala:107)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info]   Cause: java.lang.NumberFormatException: D.Dr03: For input string: "53.563"
[info]   at com.github.lwhite1.tablesaw.api.ShortColumn.addCell(ShortColumn.java:223)
[info]   at com.github.lwhite1.tablesaw.io.csv.CsvReader.read(CsvReader.java:147)
[info]   at com.github.lwhite1.tablesaw.io.csv.CsvReader.read(CsvReader.java:76)
[info]   at com.github.lwhite1.tablesaw.io.csv.CsvReader.read(CsvReader.java:96)
[info]   at com.github.lwhite1.tablesaw.api.Table.createFromCsv(Table.java:846)
[info]   at pt.inescn.utils.TableSawUtilsSpec.$anonfun$new$6(TableSawUtilsSpec.scala:107)
[info]   at pt.inescn.utils.Utils$.time(Utils.scala:10)
[info]   at pt.inescn.utils.TableSawUtilsSpec.$anonfun$new$5(TableSawUtilsSpec.scala:107)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   ...
```
On investigating this I find that the type SHORT_INT was assigned as the column type to column 258. 
All values are 0 except row 26, which is in fact 53.563. This was checked in R. I have determined that  in the call: 

```java
public static Table read(String fileName, boolean header, char delimiter, boolean skipSampling) throws IOException {
    ColumnType[] columnTypes = detectColumnTypes(fileName, header, delimiter, skipSampling);
    return read(columnTypes, true, delimiter, fileName);
  }
```
`detectColumnTypes` reads the data but for the particular column, only 0's are obtained. If I debug in this function until the loop : 

```Java
for (List<String> valuesList : columnData) {
      ColumnType detectedType = detectType(valuesList);
      columnTypes.add(detectedType);
    }
```
 
I see that `rowCount` is 528 (correct) but the `ArrayList` in `ElementData[258]` is only 89. Looking at the following code snippet, something seems amiss. Note that irrespective of skipping sampling or not, the sampling is still performed.

```Java
if (rowCount == nextRow) {
          if (skipSampling) {
            nextRow = nextRowWithoutSampling(nextRow);
          }
          nextRow = nextRow(nextRow);
        }
        rowCount++;
      }
```
Shouldn't it be something like:

```Java
if (rowCount == nextRow) {
          if (skipSampling) {
            nextRow = nextRowWithoutSampling(nextRow);
          } 
          else {
             nextRow = nextRow(nextRow);
          } 
        }
        rowCount++;
      }
```
If have included the data set (362.3kB zipped) in case you want to test this. 
 
[mdrrdesc.csv.zip](https://github.com/lwhite1/tablesaw/files/828294/mdrrdesc.csv.zip)

**Comment by lwhite1** [comment]
Yes that looks correct. Sorry. Trying to do too much in too little time. Will fix tonight

**Comment by hmf** [comment]
@lwhite1 I have changed my code to skip columns, reran my tests and all seemed to pass correctly. Seems to be working correctly now. 

Thank you.
