### ISSUE TITLE
Keep column header checks for duplicates case sensitive 

### ISSUE THREAD

**Issue by hmf** [lwhite1/tablesaw#104]
Hello,

I am testing the loading of a file using one of R's data samples (mddrDesc). The loading fails because it has headers  that are the same save for a difference in case (W and w). The header case seems to be kept as the original but the check for duplicates seems to make a case change. Can we keep the case when checking for duplicates?

TIA

**Comment by lwhite1** [comment]
I regret that we cannot do that without significant changes elsewhere. The code for referencing columns by name is also case-insensitive. 

`myTable.column("Foo").equals(myTable.column("foO")
`
would return true, for example.

This was done deliberately to make it easier to use the library interactively (as in the oft-delayed Java 9 REPL). So if we checked for duplicate column names in a case sensitive way, it would cause other problems down-stream.  

Also while I recognize that we often have to work with the data we're given, I feel that it would in most cases be a bad idea to use column names that differ only by case.

**Comment by hmf** [comment]
Ok. Thanks.
