### ISSUE TITLE
dateColumn could not get correct year

### ISSUE THREAD

**Issue by vangogh-ken** [lwhite1/tablesaw#106]
Hi, I tested the dateColumn. The result always -1 while I try to get the year, But the dateTimeColumn runs well. Please check this should be a bug or I did wrong invoking. Thank you.

                          ShortColumn year = table.dateColumn(0).year();
			  year.setName("YEAR");
			  table.addColumn(year);

			  System.out.println(table.print());

**Comment by lwhite1** [comment]
Thanks for the report. 

fixed on 0.7.7.2, which should appear on mvn central shortly.
