### ISSUE TITLE
Tablesaw does not recognize column

### ISSUE THREAD

**Issue by rakke** [lwhite1/tablesaw#107]
When trying to access Table data Tablesqw does not recognize column by name.
```Java
volumes = Table.createFromCsv("src/main/resources/input/all_reduced_2.csv");
System.out.println(volumes.structure().print());
for(int row : volumes){
    System.out.println(volumes.shortColumn("Test").get(row));
}
```
Output:
```
Structure of all_reduced_2.csv
Index Column Name Column Type 
0     ﻿Test       SHORT_INT   
1     Month       SHORT_INT   
2     MonthId     INTEGER     
3     A           CATEGORY    
4     B           CATEGORY    
5     C           CATEGORY    
6     D           CATEGORY    
7     E           CATEGORY    
8     F           CATEGORY    
9     G           CATEGORY    
10    H           CATEGORY    
11    I           CATEGORY    
12    J           CATEGORY    

Exception in thread "main" java.lang.IllegalStateException: Column Test does not exist in table all_reduced_2.csv
	at com.github.lwhite1.tablesaw.table.Relation.column(Relation.java:87)
	at com.github.lwhite1.tablesaw.table.Relation.shortColumn(Relation.java:308)
	at RevenueAnalysis.readVolumeInput(RevenueAnalysis.java:25)
	at RevenueAnalysisApp.main(RevenueAnalysisApp.java:27)
```
all_reduced.csv:
```
Test,Month,MonthId,A,B,C,D,E,F,G,H,I,J
2016,3,201603,AAA,BBB,CCC,DDD,EEE,FFF,GGG,HHH,III,JJJ
```
Runtime:
```
Windows 10
JDK 1.8.0_121
Maven 3.3.9
```

The column can be accessed using 
```Java
System.out.println(volumes.shortColumn(0).get(row));
```

**Comment by lwhite1** [comment]
Thank you for the detailed bug report. I will try to look at it this weekend: I'm not feeling too good at the moment.  Superficially, it looks like an encoding issue, where the file's encoding is not the same as the UTF encoding of the java string it's being tested against, but it needs more research.

**Comment by rakke** [comment]
Thank you for the quick reply, and thank you for building this great library. Much appreciated.

**Comment by lwhite1** [comment]
Hi, I'm sorry but I can't recreate the issue. I created a CSV file from the example you provided, but it works properly on my machine.  Unfortunately, I do not own a windows machine to test on that platform and in any case, I suspect I would need the original file. It seems very likely to me to be either an encoding issue or a platform specific bug at a fairly low level in my stack. Not sure where to take it next.

I'm not sure of the origin of your file, but perhaps you could read it into excel and try exporting it again as a new csv, being mindful of whatever options excel provides for encoding.

**Comment by rakke** [comment]
Encoding:
![image](https://cloud.githubusercontent.com/assets/1255889/24602076/918621d8-185b-11e7-971e-6b50a5ed81b1.png)

still produce same error. File attached.
[all_reduced_3.zip](https://github.com/lwhite1/tablesaw/files/889453/all_reduced_3.zip)

**Comment by lwhite1** [comment]
Ok. Pretty interesting. Sorry for the delay.

I was able to recreate the issue. It is because there is a non-visible character (/uFEFF) at the beginning of the file. This is a Beginning of Message indicator. It is recommended that it not be used in UTF-8, but is common in Microsoft-land. Java trim() does not remove it. I will find a way to strip it out and provide a fix.

**Comment by lwhite1** [comment]
fixed in 0.7.7.3.

**Comment by antoine-guillou** [comment]
Test tech.tablesaw.io.csv.CsvReaderTest.testReadFailure2 is currently failing on my machine for a very similar reason.

> Column Test does not exist in table read_failure_test2.csv

The first column name is  

> ï»¿Test

I had a quick look at it, and it seems that in the method AbstractColumn.removeUtf8Bom, UTF8_BOM = "\uFEFF" is not detected in "ï»¿Test". So the byte order mark is not removed from the column name.
But if I change UTF8_BOM to "ï»¿" it works well.

**Comment by lwhite1** [comment]
ah. i hate these Microsoft specific bugs because I can't test the fixes
fully. On my machine (a Mac) the fix makes the (Windows produced) file
readable. What OS are you running?

**Comment by antoine-guillou** [comment]
I see... I am on Windows 10.

**Comment by lwhite1** [comment]
would you mind submitting a pull request for a fix that ORs the two
variants: "\uFEFF" and  "ï»¿"?

It would be greatly appreciated.

**Comment by benmccann** [comment]
I think a cleaner fix would be to use something like UnicodeBOMInputStream when reading the CSV
https://github.com/gpakosz/UnicodeBOMInputStream/blob/master/src/net/pempek/unicode/UnicodeBOMInputStream.java

I don't really love checking for "\uFEFF" and  "ï»¿" because we should be consistent in our checks (e.g. always use the \u version). Also, there appears to be five BOMs according to UnicodeBOMInputStream and we'd only be handling two of them. And this should only be in the first characters of the file, so doing the check for every column/cell is way overkill.

**Comment by antoine-guillou** [comment]
I was also checking this git repo, and it does the job at reading read_failure_test2.csv for me.

> Reading the content of the file without skipping the BOM: ï»¿Test,Month,MonthId,A,B,C,D,E,F,G,H,I,J
> Reading the content of the file after skipping the BOM: Test,Month,MonthId,A,B,C,D,E,F,G,H,I,J

**Comment by lwhite1** [comment]
yeah, ben's solution is much better than mine. :)

**Comment by antoine-guillou** [comment]
In CsvReader, changing
>     public static Table read(File file, boolean header, char delimiter) throws IOException {
>         Reader reader = new FileReader(file);
>         return read(reader, file.getName(), true, delimiter);
>     }

to 

>     public static Table read(File file, boolean header, char delimiter) throws IOException {
>         FileInputStream fis = new FileInputStream(file);
>         UnicodeBOMInputStream ubis = new UnicodeBOMInputStream(fis);
>         ubis.skipBOM();
>         Reader reader = new InputStreamReader(ubis);
>         return read(reader, file.getName(), true, delimiter);
>     }

does the trick.
Not sure about the performance impact (is there tests to check the perf?).
Also, I don't know how maven works and how to cleanly add the extra dependency. So I can't share my mod.

**Comment by benmccann** [comment]
That file isn't packaged via Maven, so the solution in this case would be to just copy and paste the file. If you send a PR with the fix we can merge it
