### ISSUE TITLE
DateTimeColumn miss isAfter filter

### ISSUE THREAD

**Issue by lanzisun** [lwhite1/tablesaw#113]
In the ColumnReference, I can find the Filter for check LocalDateTime 'is before', but seem didn't have 'is after' filter. if this is a missing or any method replace on?

**Comment by lwhite1** [comment]
This is fixed in the next release. Not sure of the timing yet. 

There are a number of other holes and inconsistencies in the current API that will be patched then.

**Comment by lanzisun** [comment]
Well noted. and thanks for your good job.
