### ISSUE TITLE
Modularize code

### ISSUE THREAD

**Issue by benmccann** [lwhite1/tablesaw#118]
Would you be open to me sending a PR to do the following?

I'd like to split project into `tablesaw-core` and `tablesaw-plot`. I'd like to use tablesaw in a web app. So I'll use a JavaScript charting library and won't be able to use any of the Swing-based charting like `smile-plot` and `xchart`. Splitting these into a separate module would save me from having to have these extra dependencies on my classpath

**Comment by lwhite1** [comment]
Yes, it's the right thing to do.

**Comment by benmccann** [comment]
This is done
