### ISSUE TITLE
Change the sort api to allow the use of "-columnName" to indicate a descending sort

### ISSUE THREAD

**Issue by lwhite1** [lwhite1/tablesaw#15]
Sorting currently defaults to ascending order:
t.sortOn("column1", "column2");
sorts in ascending order based on the values in the two given columns:

to specify descending sorts, you have to use:
t.sortDescendingOn:("column1);

If you want to mix ascending and descending so that you sorted the tallest first by age, starting with the youngest, you have to construct a Sort object and pass that to a specialized sortOn: method. It should be possible to simply write:
sortOn("age", "-height");  // by age starting with the youngest, then by height starting with the tallest.

This can be implemented by parsing the column names and constructing a Sort object behind the scenes

**Comment by smarks** [comment]
In the example above the - prefix to height indicates the sort order?

**Comment by smarks** [comment]
also, 

 * table.sortOn(first("Year", DESCEND).next("State", ASCEND));

is another way of doing 

sortOn("Year", "-State");

right?

**Comment by lwhite1** [comment]
>In the example above the - prefix to height indicates the sort order?

It indicates that the sort on height is in descending order, while its absence on age indicates that that sort  is in (standard) ascending order.

**Comment by lwhite1** [comment]
> table.sortOn(first("Year", DESCEND).next("State", ASCEND));
> is another way of doing
> sortOn("Year", "-State");
> right?

Yes, but the general idea is to convert the latter to the former, and remove the former from the public API (as it is unsightly)

**Comment by smarks** [comment]
OK I get it now. I am not sure I agree that is it unsightly but can also the advantage of parsing the column name to get the sort order. If a user ever named a column -my_column they would have to specify --my_column which is awkward but probably won't happen in real life. Also, do you want to support the + to indicate the default explicitly?

**Comment by lwhite1** [comment]
Yeah, I'm ok with the -- issue and not having the + variation, although I'd
add it if there were infinite time

**Comment by smarks** [comment]
Something like this then

 /**
     * Returns a copy of this table sorted on the given column names, applied in order,
     * <p>
     * if column name starts with - then sort that column descending otherwise sort ascending
     */
    public Table sortOn(String... columnNames) {
        Sort key = null;
        Order order = null;
        for (String columnName : columnNames) {
              order = getOrder(columnName);
            if (key == null) { // first time through
                order = getOrder(columnName);
                key = first(columnName, order);
            } else {
                key.next(columnName, order);
            }

        }
        return sortOn(key);
    }

    private Order getOrder(String columnName) {
        Order order;
        if (columnName.startsWith("-")) {
            order = Order.DESCEND;
        } else {
            order = Order.ASCEND;
        }
        return order;
    }

**Comment by lwhite1** [comment]
The second line here is redundant:
```
 if (key == null) { // first time through
                order = getOrder(columnName);
 
```

**Comment by smarks** [comment]
Yeah, I see that. It was even more redundant before. 
I also initially did not check for the -- case.  That will slow things up. Do you want me to do that?
Also, I  used startsWidth, it might be a bit faster if I converted the string to an array of char (If it was not empty) and just checked the first location.  Is that too much optimization?

**Comment by smarks** [comment]
also, what are your thoughts about adding a equals method to the table class?

**Comment by lwhite1** [comment]
If you peel off the - and it blows up because they named their column -name, not a big deal i think. That's what I tried to say above anyway. The other thing would be to force them to not do that in the column name setter. You'd have to throw a runtime exception there and add to the javadoc.

i don't think startswith would be any slower, plus it is only called once per sort, so it wouldn't matter much.

I guess you could add an equals method. For testing? For a big table it would take a long time to compare every value. I know it's standard, but i think the typical use case doesn't involve a lot of tables that may or may not be the same.

**Comment by lwhite1** [comment]
if you go down the setName() route, it's in the AbstractColumn class, but you'd also have to check for direct references to _name_ from constructors.

**Comment by smarks** [comment]
two things - where do I set it so I get notified when you reply 

another way (which I am not recommending per say) is to find the column name from the list in the table and check to see if it starts with - or not. That would be the most robust but slowest way to handle this case. I won't do that as it doesn't sound like you think it is worth it. 

ok, three things, the end of result of sorting tables using tablesaw should be same the same result as using excel to sort them? (If yes, I am doing something wrong).

**Comment by lwhite1** [comment]
1. https://help.github.com/articles/managing-notification-delivery-methods/

2. speed doesn't matter for this; all the time will be spent sorting data. 
I suppose that works

3. i think so, but that's not enough info for me to really help. Does it look like a logically correct sort? Does it sort ok if you don't use the new '-' approach? Examples?

**Comment by smarks** [comment]
It says I am subscribed but  I am not getting notices. : <

just pushed what I think will be final code with one test that verifies. I am writing more tests to verify all cases so code might change, but hopefully not much.

**Comment by lwhite1** [comment]
closed. implemented. Thank you, Spencer.
