### ISSUE TITLE
lots of functions in FloatColumn seem to be broken

### ISSUE THREAD

**Issue by awclives** [lwhite1/tablesaw#46]
here is an example:
`    public FloatColumn round() {
        FloatColumn newColumn = create(this.name() + "[rounded]");

        for(int r = 0; r < this.size(); ++r) {
            float value = this.data.getFloat(r);
            newColumn.set(r, (float)Math.round(value));
        }

        return newColumn;
    }`

the set fails because the length of newColumn is 0.

**Comment by lwhite1** [comment]
reviewing

**Comment by lwhite1** [comment]
pushed fix to master. Opened an issue to address the lack of tests.  

thanks.

**Comment by awclives** [comment]
shouldn't these preallocate the array at the start?  would be a lot more efficient than growing every time.

**Comment by lwhite1** [comment]
They should. i just wanted to get something working before I went offline. It will be a very quick fix, probably pushed later today.

**Comment by lwhite1** [comment]
actually, it was so quick i just did it.  Thanks again
