### ISSUE TITLE
is there no way to copy columns or tables?

### ISSUE THREAD

**Issue by awclives** [lwhite1/tablesaw#49]
I can't see one.  If there isn't, I think we should add a way of copying both columns and tables.  Otherwise you add a column form one Table to another, modify that column, and screw up the original Table.  

Clearly with the big-data type workflows, you want to avoid copying but Table will also be useful for many cases where people are dealing with much smaller things, for instance a Table of summary statistics that you want to save as csv.  Calling copy in these cases won't be an issue.  

The other approach is to make Column immutable and so you don't have to defensively copy.  It may be too late for that here.

**Comment by lwhite1** [comment]
I have been considering making Table immutable. Currently very few operations mutate the original (both sort and select, for example, return new tables). Making columns immutable would be work, but also, maybe, make it harder for users (for the same reason people use other immutable collections only infrequently. 

Still, it has some advantages as you point out. I'll think on it some more over the weekend. 

If you have a table of summary stats, saving as a CSV doesn't involve copying the table, just streaming the records to a file, so I guess I'm not completely understanding. I hadn't considered that people would want an exact copy of a table or column, but certainly, it would not be hard to implement.

**Comment by awclives** [comment]
The example where mutability of columns without copying is an issue is as follows.

Object A owns Table A.  Object B needs the info from Table A so it asks Object A for it and then adds Table A's columns to its newly created table, Table B.  Now Object B decides to add to Table B a new row containing the averages of all the columns in Table B.  The problem is that this addition would also add to the columns in Table A.  

To solve this, either columns should be immutable or there should be an easy way for Object A to give Object B a deep copy of Table B.

**Comment by lwhite1** [comment]
Added (at least until the mutability question is resolved) a deep copy function for each column: column.copy();

Will open an enhancement issue where column mutability can be pondered.
