### ISSUE TITLE
Table.append bug

### ISSUE THREAD

**Issue by awclives** [lwhite1/tablesaw#62]
`  public void append(Table tableToAppend) {
    for (Column column : columnList) {
      Column columnToAppend = tableToAppend.column(column.name());
      for (int i = 0; i < columnToAppend.size(); i++) {
        column.append(columnToAppend);
      }
    }
  }`

should be

`  public void append(Table tableToAppend) {
    for (Column column : columnList) {
      Column columnToAppend = tableToAppend.column(column.name());
        column.append(columnToAppend);
    }
  }`

**Comment by lwhite1** [comment]
will fix later tonight

**Comment by lwhite1** [comment]
fixed in commit 967e9a6
