### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by smarks** [lwhite1/tablesaw#67]
mvn test produces these failures:

Tests in error:
  testMean(com.github.lwhite1.tablesaw.aggregator.NumericReduceUtilsTest): com/github/lwhite1/tablesaw/io/CsvReader
  testGroupMean(com.github.lwhite1.tablesaw.aggregator.NumericReduceUtilsTest): com/github/lwhite1/tablesaw/io/CsvReader
  initializationError(com.github.lwhite1.tablesaw.columns.BooleanColumnTest): Lcom/github/lwhite1/tablesaw/columns/BooleanColumn;
  initializationError(com.github.lwhite1.tablesaw.columns.CategoryColumnTest): Lcom/github/lwhite1/tablesaw/columns/CategoryColumn;
  testMax(com.github.lwhite1.tablesaw.columns.FloatColumnTest): com/github/lwhite1/tablesaw/columns/FloatColumn
  testMin(com.github.lwhite1.tablesaw.columns.FloatColumnTest): com/github/lwhite1/tablesaw/columns/FloatColumn
  testIsEqualTo(com.github.lwhite1.tablesaw.columns.FloatColumnTest): tried to access method com.github.lwhite1.tablesaw.api.Table.<init>(Ljava/lang/String;)V from class com.github.lwhite1.tablesaw.columns.FloatColumnTest
  testSort(com.github.lwhite1.tablesaw.columns.FloatColumnTest): com/github/lwhite1/tablesaw/columns/FloatColumn
  testIsLessThan(com.github.lwhite1.tablesaw.columns.FloatColumnTest): tried to access method com.github.lwhite1.tablesaw.api.Table.<init>(Ljava/lang/String;)V from class com.github.lwhite1.tablesaw.columns.FloatColumnTest
  testIsGreaterThan(com.github.lwhite1.tablesaw.columns.FloatColumnTest): tried to access method com.github.lwhite1.tablesaw.api.Table.<init>(Ljava/lang/String;)V from class com.github.lwhite1.tablesaw.columns.FloatColumnTest
  initializationError(com.github.lwhite1.tablesaw.columns.IntColumnTest): Lcom/github/lwhite1/tablesaw/columns/IntColumn;
  initializationError(com.github.lwhite1.tablesaw.columns.LocalDateColumnTest): Lcom/github/lwhite1/tablesaw/columns/LocalDateColumn;
  testName(com.github.lwhite1.tablesaw.integration.SortTest): com/github/lwhite1/tablesaw/columns/IntColumn
  initializationError(com.github.lwhite1.tablesaw.mapper.DateTimeMapUtilsTest): Lcom/github/lwhite1/tablesaw/columns/LocalDateTimeColumn;

**Comment by smarks** [comment]
Should I try to fix them?

**Comment by lwhite1** [comment]
can't reproduce.  LMK if it doesn't cure itself next time you're in the code.

**Comment by smarks** [comment]
resolved
