### ISSUE TITLE
origin of start and end

### ISSUE THREAD

**Issue by holgerbrandl** [lwhite1/tablesaw#75]
Hi, nice library!

Where do `start` and  `end` come from in the landing page example https://github.com/lwhite1/tablesaw#easy-to-use-is-easy-to-say  ?

Is it possible to add constant values as new columns to an existing table?

**Comment by lwhite1** [comment]
Good questions! 
Question 1:  My bad, I had made the original example overly complex and then edited it without re-compiling.  I just threw in an update to the readme which shows how to create those columns by combining a date column and a time column into a date time column (one called start, and the other end). It's still not a great example (doesn't handle crossing date line) so I'll be revising in the future (have to go to work now). 

You can add a new column to the table as long as it's the same size as the other columns:  That's illustrated in the example where the new duration column is added to ops table.

myTable.addColumn(foo);

**Comment by holgerbrandl** [comment]
Thanks!
