### ISSUE TITLE
The colors.txt file isn't found when run from inside jar

### ISSUE THREAD

**Issue by richiethom** [lwhite1/tablesaw#79]
When using a jar built from the head of your master branch, the file colors.txt isn't found.

I have fixed this in the following branch by moving colors.txt into a the resources folder and using the classloader to load the file from the jar.

https://github.com/richiethom/tablesaw/tree/colourfilefix

I've not created a pull request as I wasn't sure if this was a work in progress or not.

**Comment by lwhite1** [comment]
Hi Richie,
If you wouldn't mind creating a pull-request, it would be greatly
appreciated.

larry

**Comment by richiethom** [comment]
Done :) #81

**Comment by lwhite1** [comment]
merged
