### ISSUE TITLE
Feature: Autodetect CSV column type

### ISSUE THREAD

**Issue by lwhite1** [lwhite1/tablesaw#8]
so reading CSV doesn't require columns to be pre-defined, which is tedious for wide files

**Comment by douglasArantes** [comment]
What approach will you use?

**Comment by lwhite1** [comment]
I haven't decided. I planned to look at the javascript library wrangler (https://github.com/StanfordHCI/wrangler) and the java library OpenRefine. The import package for that project can be found here: https://github.com/OpenRefine/OpenRefine/tree/master/main/src/com/google/refine/importing. 

Of course, if we integrate with Smile, a classifier might be a natural approach :)

**Comment by lwhite1** [comment]
done.
The CsvReader class has new set of _read()_ methods that estimate the column types based on a sample of input data.
If that estimate is incorrect, the methods _detectColumnTypes()_ and _printColumnTypes()_ can help. The latter produces a string that contains the list of estimated column types, along with their position in the file and names, in a format that can be directly pasted into an array literal definition:

**ColumnType[] types = {**
      LOCAL_DATE, // 0     date
      SHORT_INT,    // 1     approval
      CATEGORY,     // 2     who
**}**
