### ISSUE TITLE
large/inconsistent first cell value of columns throw exception - bug

### ISSUE THREAD

**Issue by adn4n** [lwhite1/tablesaw#83]
Importing the following 2x2 csv file as a table throws: `Error while addding cell from row 1 and column column1(position:0): column1: Value out of range. Value:"32768" Radix:10`.

`column1,column2`
`32767,2147483648`
`1,32768`

However, if you just switch the first line `32767,2147483648` with the second `1,32768`, everything works fine.

In the case of FLOAT columns, importing the following 2x2 csv file as a table throws: `Error while addding cell from row 1 and column column1(position:0): column1: For input string: "1.1"`.

`column1,column2`
`1.1,2.1`
`1,2`

However, just switching the first line `1.1,2.1` with the second `1,2` makes it work.

**Comment by lwhite1** [comment]
Fixed.

**Comment by adn4n** [comment]
Thanks.

**Comment by lwhite1** [comment]
thanks for reporting that issue. Much appreciated.
