### ISSUE TITLE
Copying a CategoryColumn breaks selectWhere statements

### ISSUE THREAD

**Issue by benparkinson** [lwhite1/tablesaw#90]
When you call CategoryColumn#copy(), the internal valueToKey DictionaryMap does not set its defaultReturnValue in the copy constructor. In the normal constructor this is set to -1, but in the constructor called by copy() this is not set, and so is left as default (0). This means that when you call selectWhere on the copied column with any String, the first value in the column is returned if it is not found.

Below unit test fails on the last two lines:

`   @Test`
`    public void sanityTest() {`
`        String col1Name = "Name";`
`        CategoryColumn nameCol = new CategoryColumn(col1Name, 1);`
`        nameCol.add("TableSaw");`
`        String verColName = "Version";`
`        IntColumn verCol = new IntColumn(verColName, 1);`
`        verCol.add(1);`
`        Table table = Table.create(null, nameCol, verCol);`
`        Table tableSawTable = table.selectWhere(column(col1Name).isEqualTo("TableSaw"));`
`        Assert.assertEquals(1, tableSawTable.column(col1Name).size());`
`        Assert.assertEquals(1, tableSawTable.column(verColName).size());`
`        // copy columns`
`        Table table2 = Table.create(null, nameCol.copy(), verCol.copy());`
`        Assert.assertEquals(1, table2.column(col1Name).size());`
`        Assert.assertEquals(1, table2.column(verColName).size());`
`        Table bogusTable = table2.selectWhere(column(col1Name).isEqualTo("???????"));`
`        Assert.assertEquals(0, bogusTable.column(col1Name).size());`
`        Assert.assertEquals(0, bogusTable.column(verColName).size());`
`    }`

**Comment by lwhite1** [comment]
closing.  
Thank you for such a clear analysis of the issue. That's such a big help. --larry

**Comment by benparkinson** [comment]
Thanks!
