### ISSUE TITLE
CategoryColumn.getDummies() assigns values incorrectly

### ISSUE THREAD

**Issue by jgainesau** [lwhite1/tablesaw#93]
Line 384 of CategoryColumn is supposed to look up the category of a given value as part of the process of dummy-encoding the column.

But instead the call `get(next)` first looks up the category at the row indicated by the parameter `next`, and then looks up its category.

Line 384 should probably be: 

`String category = lookupTable.get(next);`

The unit test passes because, while it verifies that the correct number of dummy columns is created, it does not check that the distribution of values is correct across those columns.

**Comment by lwhite1** [comment]
closing fixed.
