### ISSUE TITLE
Get and remove a column

### ISSUE THREAD

**Issue by douglasArantes** [lwhite1/tablesaw#94]
I think would be interesting a method that return a column by index, and remove this column from the Table object.

Something like:

` Table table = Table.createFromCsv("kaggle/Allstate/train.csv");`
`table.removeColumn(0); // ID` 
`Column labels = table.getColumnAndRemove(131);` 

The table object will contain just the training data to feed the machine learning algorithm.

What do you think, some better alternative?

Congratulations for your work on this project. I hope it continue evolving, and integrating with others languages of the JVM like Scala and Kotlin.

**Comment by lwhite1** [comment]
Added methods: 

getAndRemoveColumn(String columnName);
getAndRemoveColumn(int columnIndex);

in release 0.7.6.8

**Comment by douglasArantes** [comment]
Nice!
