### ISSUE TITLE
Offer  a "thin" jar instead of a "fat" jar ?

### ISSUE THREAD

**Issue by locuslin** [lwhite1/tablesaw#97]
The jar deployed in Maven now is a fat jar,combing all its dependencies into itself,which is quite unfriendly for users who might have a dependency of different version.  
Would you mind deploying a "thin" jar (might with a different classfier) into Maven  ?

**Comment by lwhite1** [comment]
Sorry for your trouble.
I doubt I will get around to creating a thin jar.  Perhaps you can build one from source?

**Comment by locuslin** [comment]
It's OK for me to build it temporarily.Thanks for your reply.
